consul:
  image: rancher/dns-service
  links:
    - consul-server:consul-server

registrator:
  image: gliderlabs/registrator:v6
  command:
    - -resync
    - '300'
    - -ttl
    - '300'
    - -ttl-refresh
    - '60'
    - consul://localhost:8500
  net: host
  privileged: true
  tty: true
  stdin_open: true
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  labels:
    io.rancher.container.dns: 'true'
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  links:
    - consul-agent:consul-agent

consul-agent:
  image: nextrevision/consul-rancher:latest
  command: agent
  net: host
  tty: true
  stdin_open: true
  labels:
    io.rancher.container.dns: 'true'
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=consul-server
  links:
    - consul-server:consul-server

consul-server:
  image: nextrevision/consul-rancher:latest
  command: server
  net: host
  tty: true
  stdin_open: true
  labels:
    io.rancher.container.dns: 'true'
    io.rancher.sidekicks: consul-data
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=consul-server
    io.rancher.container.hostname_override: container_name

consul-data:
  image: nextrevision/consul-rancher:latest
  hostname: consul-server
  tty: true
  stdin_open: true
  entrypoint: /bin/true
  volumes:
    - /data
  labels:
    io.rancher.container.dns: 'true'
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
